smtp:
    server: '<SMTP_SERVER>'
    port: <SMTP_PORT>
    user: '<EMAIL_FROM>'
    password: '<EMAIL_PASS>'
email:
    from: '<EMAIL_FROM>'
    to: '<EMAIL_TO>'
dns:
  domain: '<DOMAIN>'
  ip: '<IP>'